---
title: "README"
author: "Frank Fichtenmueller"
date: "14 November 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Application ready Codebase for Graph based Machine Learning in R

Starting out with Code along the Coursera Course on Graphical Propabilistc Models by Stanford University, i will describe the technical implementation of machine Learning Models for Semantic Data in R and Python. 

### Scope

This repo contains work on the following subfields:

- **General syntax** for working with graph based Data in R
- **Special Introduction** of Syntax for the most common Libraries 
- **Application based examples** of implementation best practice
- **Graph based Machine Learning** applications and detailled usecases


Packages contained in this repo:

- **biocLite**
- **gRain**
- **gRbase** : 
- **Rgraphviz** : for visualizing graphs


The content of this repo is constructed to be easily re-applicable to further projects, and store new information along 
the Development of my work. 

Everyone is invited to join the creation and discuss the content of the repo. 

