---
title: "Databases in R"
output: html_notebook
---

## Working with Datbase Connections in R
As well as working with local in-memory data like data frames and data tables, dplyr also works with remote on-disk data stored in databases. Generally, if your data fits in memory there is no advantage to putting it in a database: it will only be slower and more hassle. The reason you’d want to use dplyr with a database is because either your data is already in a database (and you don’t want to work with static csv files that someone else has dumped out for you), or you have so much data that it does not fit in memory and you have to use a database. Currently dplyr supports the three most popular open source databases (sqlite, mysql and postgresql), and google’s bigquery.

Since R almost exclusively works with in-memory data, if you do have a lot of data in a database, you can’t just dump it into R. Instead, you’ll have to work with subsets or aggregates. dplyr aims to make this task as easy as possible. If you’re working with large data, it’s also likely that you’ll need support to get the data into the database and to ensure you have the right indices for good performance. While dplyr provides some simple tools to help with these tasks, they are no substitute for a local expert.


### Connecting to a database with dplyr

As the dplyr commands are directly translated into all usual types of database queries using a database API from the `DBI Package` to set.

The commands are:

- `src_sqlite()`:       To connect to a `SQLite` Database
- `src_mysql()` :       To connect to a `MySQL` Database
- `src_postgres()`:     To connect to a `PostgreSQL` Database

Exercises:
```{r, eval=FALSE, include=FALSE}
require(DBI)
require(dplyr)
install.packages("DBI", dependencies = TRUE)
install.packages("RPostgreSQL")


# Example connection
air <- src_postgres(dbname="airontime", 
                    host="sol-eng-sparklyr.cyii7eabibhu.us-east-1.redshift.amazonaws.com", 
                    port="5439", 
                    user="redshift_user",
                    password="ABCd4321")

# Once we got the connection, we can use it to send the required commands and work with it as an object in R's Namespace
src_tbls(air)
"flights" "planes"

# Then create table references to work with in R
flights <- tbl(air, "flights")
planes <- tbl(air, "planes")

# Manipulate table objects in R
flights <-  left_join(flights, planes, by="tailnum")

# the query will be translated into sql code and send to the database where it is performed. The result will be headed for 10 lines.

# Collect results in R. This applies, when we want to get the complete download from the database for inspection etc..
flights <- collect(flights)

# To learn more about working on databases in Dplyr 
vignette("databases", package="dplyr")
```