---
title: "Tidying Datasets"
output: html_notebook
---

### Cleaning up messy datasets with the help of `tidyr` package functions
```{r}
require(tidyr)
require(dplyr)
require(DSR)
```

The DSR Package loads a couple of messy datasets to play with.
```{r}
table1
#  This is the clean and tidied up final version
```

```{r}
table2
# Here the key and values are combined in columns and need to be spread out again

table2 %>% spread(key, value)
# The columns will be automatically named appropriatly, and the columns will be spread according to the factor levels in the `key` column
```

```{r}
table3
# Here we have the values for the instances compared to the overall population per year in the given countries.
# We want to be able to calculate on both of these values individually, so we need to separate them into their own columns.

table3 %>% separate(rate, into=c("cases", "population"))
# We pass the column to be seperated and the column names to store the information into as a concatinated string
```

Now we can work a couple of tidying examples

```{r}
who
# The dataset spreads the values out over all columns, which produces lots of empty rows
who %>% gather("key", "value", 5:60)
# Now we have all values in one column, and only need to spread out the information combined in the key column
who %>% gather("key", "value", 5:60) %>% separate(key, into=c("new", "type", "sexage")) %>% separate(sexage, into=c("Sex", "Age"), sep=1)


```

